import { PropertyFormValues, PROPERTY_SUBTYPES } from "@/types/property";

export const INITIAL_PROPERTY_VALUES: PropertyFormValues = {
     category: '',
      name: '',
      address: '',
      locationId: '',
      latitude: '',
      longitude: '',
      totalSurface: '',
      coveredSurface: '',
      description: '',
      type: '' ,
      subtype: '',
      currency: 'USD',
      price: '',
      residential: { isNew: false, age: '', rooms: '', bathrooms: '', hasPool: false, hasGrill: false, hasGarden: false, hasAC: false, hasGarage: false, hasLaundry: false, hasDressingRoom: false, hasGym: false, isFurnished: false, hasNaturalGas: false },
      commercial: { isNew: false, age: '', rooms: '', bathrooms: '', hasAC: false, hasParking: false, hasRollingShutter: false, hasKitchen: false, hasFireProtection: false },
      industrial: { isNew: false, age: '', height: '', offices: '', bathrooms: '', hasParking: false, hasFullSoul: false, hasThreePhasePower: false, hasIndustrialGas: false, hasFireNetwork: false, isInsidePark: false, zonification: '' },
      land: { frontMeters: '', backMeters: '', hasWaterLine:false, hasGasLine: false, hasSewerLine: false, hasElectricity: false, isFenced: false, isGatedNeighborhood: false },
      images: [],
      slug: '',
      videoUrl: '',
      pdfUrl: '',
      isPublished: false,
      colleagueId: '',
      colleague: { fullName: '', agencyName: '', phoneNumber: '', email: '' },
      ownerId: '',
      owner: { fullName: '', phoneNumber: '', email: '' },
      propertySource: 'ms_propia',
      agentId: '',
      agent: { fullName: '', phoneNumber: '', email: '' },
      privateNotes: '',
      internalDocsUrls: []
};
